"""测评管理数据库迁移.

Revision ID: 20251201_01_assessments
Revises: 20251130_01_job_positions
Create Date: 2025-12-01

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '20251201_01_assessments'
down_revision = '20251130_01_job_positions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # 创建 questionnaires 表
    op.create_table(
        'questionnaires',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('questions_count', sa.Integer(), nullable=False),
        sa.Column('estimated_minutes', sa.Integer(), nullable=False),
        sa.Column('questions_data', sa.JSON(), nullable=False),
        sa.Column('scoring_rules', sa.JSON(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaires_name'), 'questionnaires', ['name'], unique=False)
    
    # 创建 assessments 表
    op.create_table(
        'assessments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('questionnaire_id', sa.Integer(), nullable=False),
        sa.Column('valid_from', sa.DateTime(), nullable=False),
        sa.Column('valid_until', sa.DateTime(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('qr_code_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_assessments_code'), 'assessments', ['code'], unique=True)
    
    # 创建 submissions 表
    op.create_table(
        'submissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('assessment_id', sa.Integer(), nullable=False),
        sa.Column('questionnaire_id', sa.Integer(), nullable=False),
        sa.Column('candidate_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('candidate_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('candidate_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('target_position', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('answers', sa.JSON(), nullable=False),
        sa.Column('scores', sa.JSON(), nullable=False),
        sa.Column('total_score', sa.Integer(), nullable=True),
        sa.Column('grade', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('submitted_at', sa.DateTime(), nullable=True),
        sa.Column('candidate_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
        sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnaires.id'], ),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_submissions_code'), 'submissions', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_submissions_code'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_assessments_code'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_questionnaires_name'), table_name='questionnaires')
    op.drop_table('questionnaires')
    # ### end Alembic commands ###

